# Generated by Django 5.1.7 on 2025-03-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Module name")),
                (
                    "identifier",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Module identifier"
                    ),
                ),
                ("version", models.CharField(max_length=20, verbose_name="Version")),
                (
                    "installed",
                    models.BooleanField(default=False, verbose_name="Installed"),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Active")),
                (
                    "install_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Install date"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ModuleField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Model name"),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="Field name"),
                ),
                (
                    "field_type",
                    models.CharField(max_length=100, verbose_name="Field type"),
                ),
                (
                    "field_params",
                    models.JSONField(default=dict, verbose_name="Field parameters"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="module_engine.module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module field",
                "verbose_name_plural": "Module fields",
                "unique_together": {("module", "model_name", "field_name")},
            },
        ),
    ]
